# Generated by Django 4.0.3 on 2022-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('cpass', models.CharField(max_length=15)),
            ],
        ),
    ]
