# Generated by Django 3.2.12 on 2022-04-24 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveryman', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.CharField(default=0, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=111)),
                ('phone', models.CharField(max_length=111)),
                ('status', models.CharField(default=0, max_length=111)),
                ('payment_type', models.CharField(default=0, max_length=111)),
                ('payment_ref', models.CharField(default=0, max_length=111)),
                ('date', models.DateField()),
                ('dman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryman.delivery')),
                ('order_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.users')),
            ],
        ),
    ]
